services:
  web:
    image: pictionary-react:1.0       
    container_name: pictionary-container
    ports:
      - "${PORT}:3000"                
    env_file:
      - .env                          
    volumes:
        - ./client/src:/app/src
        - ./client/public:/app/public
        - app-data:/app/node_modules               
    restart: unless-stopped            
    healthcheck:                        
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - pictionary-network           

networks:
  pictionary-network:
    driver: bridge                     

volumes:
  app-data: {}